# Generated by Django 5.2.8 on 2025-11-22 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_processor', '0002_add_ocr_fields'),
        ('file_processor', '0002_pdfconversion_ocr_status_pdfconversion_ocr_text'),
    ]

    operations = [
    ]
