# Generated by Django 5.2.8 on 2025-11-22 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_processor', '0003_add_analysis_type'),
        ('file_processor', '0003_merge_20251122_1014'),
    ]

    operations = [
    ]
