# Generated by Django 5.2.8 on 2025-11-22 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(blank=True, help_text='Upload video file', null=True, upload_to='videos/')),
                ('source_type', models.CharField(choices=[('file', 'File Upload'), ('webcam', 'Browser Webcam')], default='file', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_frames', models.IntegerField(default=0)),
                ('processed_frames', models.IntegerField(default=0)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='video_detections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_number', models.IntegerField()),
                ('timestamp', models.FloatField(help_text='Timestamp in seconds')),
                ('detections', models.JSONField(default=list, help_text='List of detected objects')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video_detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='video_detection.videodetection')),
            ],
            options={
                'ordering': ['frame_number'],
            },
        ),
    ]
